- name: Retrieve idmserver DNS name.
  hosts: bastions
  become: yes
  tasks:
    - package:
        name: bind-utils
        state: present
    - command: dig +short +onesoa -x "{{ ansible_default_ipv4.address }}"
      register: dig_out
    - name: Export idmserver node name.
      set_fact:
        node_dns_name: "{{ dig_out.stdout_lines[0][:-1] }}"
      delegate_facts: yes
      delegate_to: "{{ item }}"
      with_items: "{{ groups.all }}"

- name: Set IPA server variables
  hosts: bastions
  become: yes
  tasks:
    - name: Set variables.
      set_fact:
        ipaserver_domain: example.com
        ipaserver_realm: EXAMPLE.COM
        ipaserver_setup_dns: no
        ipaserver_auto_forwarders: no
        ipaadmin_password: 'r3dh4t1!'
        ipadm_password: 'r3dh4t1!'

- name: Set IPA client variables
  hosts: idm
  become: yes
  tasks:
    - name: Set variables.
      set_fact:
        ipaserver_domain: example.com
        ipaserver_realm: EXAMPLE.COM
        ipaserver_setup_dns: no
        ipaserver_auto_forwarders: no
        ipaadmin_password: 'r3dh4t1!'
        ipadm_password: 'r3dh4t1!'
        ipaclient_mkhomedir: yes
        ipaclient_no_dns_lookup: yes
        ipaclient_servers:
          - "{{ node_dns_name }}"

- name: Deploy role ipaserver to idmserver
  hosts: bastions
  become: yes
  roles:
    - role: ipaserver
      state: present

- name: Deploy role ipaclient to idm nodes 1 and 2
  hosts: idm
  become: yes
  roles:
    - role: ipaclient
      state: present
