- name: Step 005 Post Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 005 Post Software"


    - name: print out user.info
      agnosticd_user_info:
        msg: "{{ item }}"
      loop:
        - "Remote desktop password: {{ remote_desktop_password }}"
        - ""
        - "ssh -L 5901:localhost:5901 {{ remote_user }}@<IP_ADDRESS>"
        - ""
        - "vncviewer localhost:1"
        - ""

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
