---
#
# AgnosticD vars configuration file
# 
# Summit 2020 Hands-On Lab:
# RHEL Security
#
# This configuration deploys a RHEL8 bastion and 1 node.
#
# Rev. 2/6/2020
#
# Usage:
#
# mkdir <some-dir>
# cd <some-dir>
# git clone https://github.com/RedHatDemos/SecurityDemos/tree/master/2020Labs/RHELSecurity/ansible/agnosticd
# cd angnosticd/ansible
# ansible-playbook main.yml -e @../../../myconfigs/sample_vars.yml -e @/Users/lkerner/.aws/credentials
#

#
# Destroy the config.
#
# ansible-playbook -e @../../../myconfigs/sample_vars.yml -e @/Users/lkerner/.aws/opentlc-aws-creds.yaml  configs/rhel-security/destroy_env.yml
#
#env_type: rhel-security       # Name of config to deploy
env_type: rhel-custom-security-content       # Name of config to deploy
email: email@example.com              # User info for notifications

guid: XXXX                                    # Your Global UNIQUE Identifier

output_dir: /tmp/workdir                # Writable working scratch directory
subdomain_base_suffix: .sandbox1234.opentlc.com   # Your domain used with guid in FQDN
HostedZoneId: aaaaaaaaaaaaaaaaaaaaaaaa # You will need to change this
aws_access_key_id: CCCCCCCCCCCCCCCC
aws_secret_access_key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

# see roles/rhel-graphical/vars/main.yml
remote_desktop_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters,digits') }}"

# Satellite 
repo_method: satellite
satellite_url: labsat.opentlc.com
satellite_activationkey: rhel8-summit
satellite_org: Red_Hat_GPTE_Labs
use_content_view: true

# Cloud specfic (AWS) settings.
cloud_provider: ec2                     # Which AgnosticD Cloud Provider to use
aws_region: us-east-1                   # AWS Region to deploy in
key_name: id_rsa              # Keyname must exist in AWS

#
# Security Groups
#
security_groups:
  - name: RemoteDesktopRDPSG
    rules:
    - name: RemoteDesktopXRDP
      description: "RemoteDesktopXRDP"
      from_port: 3389
      to_port: 3389
      protocol: tcp
      cidr: "0.0.0.0/0"
      rule_type: Ingress
  - name: RemoteDesktopVNCSG
    rules:
    - name: RemoteDesktopTigerVNC
      description: "RemoteDesktopTigerVNC"
      from_port: 5901
      to_port: 5901
      protocol: tcp
      cidr: "0.0.0.0/0"
      rule_type: Ingress

#
# This key pair will get injected into /root/.ssh on all hosts.
# ssh private key:
#
ansible_ssh_private_key_file: ~/.ssh/id_rsa

#
# Package install
# 
# Run a full yum update and install packages
#
update_packages: true
common_packages:
  - python3
  - unzip
  - bash-completion
  - tmux
  - wget
  - git
  - vim-enhanced
  - at
  - podman
  - buildah
  - skopeo
